name: UHC-Manager
main: com.nthportal.uhc.core.UHCPlugin
author: NthPortal
version: 2.0.0-SNAPSHOT

commands:
  uhc:
    description: Control the UHC game
    usage: /uhc <start|stop|pause|resume>
    permission: uhc-manager.uhc
    permission-message: You don't have permission to run this command
  uhc-conf:
    description: Configure the UHC game
    usage: |
      /uhc-conf <reload|help>
      /uhc-conf episode-length [LENGTH IN MINUTES]
      /uhc-conf countdown-from [NUMBER]
    permission: uhc-manager.configure
    permission-message: You don't have permission to run this command
  uhc-test:
    description: Test UHC Events
    usage: |
      /uhc-test <countdown-start|full-countdown|start|full-start|stop|pause|resume>
      /uhc-test <countdown-mark|episode-change|minute> <NUMBER>
      /uhc-test <death> <PLAYER>
    permission: uhc-manager.configure
    permission-message: You don't have permission to run this command
